she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [ 
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story', views.AddStoryView.as_view(), name='newStory'),
    # path('sort-story', views.SortStoryView.as_view(), name='sortStory')

] 

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from user import views as user_views
# We are including the below to serve static images in development
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include ('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    # path('sort/<int:pk>', user_views.UserDetailView.as_view(), name='sort')
]

#Adding the below to serve static images in development - this allows media root and media url to work on the profile page
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/user/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import profile

app_name = 'user'

urlpatterns = [
    path(
        'create-account', 
        CreateAccountView.as_view(),
        name='createAccount'
    ),

    path('profile', profile, name='profile')
    #when we create profile in views.py, we did not create it as a 'view'
]

she_codes_news/news/models.py
from django.db import models


from django.db import models
from django.contrib.auth import get_user_model



class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    #author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(max_length = 200, default="https://picsum.photos/199")

    #this is so it names each news after their titles rather than News Story object(X) - so when News are visible on the admin page they would then appear with their titles
    def __str__(self):
        return self.title

she_codes_news/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
#from django.contrib.auth.models import User



# Create your models here.

class Profile(models.Model):
    # user = models.OneToOneField("user.CustomUser", on_delete=models.CASCADE)
    # image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    
    pass
    def __str__(self):
        return f'{self.user.username} Profile'
    # Decided to include the image as a field in the CustomUser class instead of creating a profile class.

class CustomUser(AbstractUser):
    #this is where I would add custom fields
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')


    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms 
from django.forms import ModelForm 
from .models import NewsStory 
 
 
class StoryForm(ModelForm): 
    class Meta: 
        model = NewsStory 
        fields = ['title', 'pub_date', 'content', 'image_url'] 
        widgets = { 
        'pub_date': forms.DateInput(format=('%m/%d/%Y'), 
        attrs={'class':'form-control', 'placeholder':'Select a date', 
        'type':'date'}), 
        } 

she_codes_news/user/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm
)

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'image']
    
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'image']        

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory #you import classes from models.py, classes are tables in the database
from django.urls import reverse_lazy
from .forms import StoryForm 
#from django.contrib.auth.decorators import login_required



class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date').all()[:4]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')
        #ordering by date
        context['user_stories'] = NewsStory.objects.order_by('author')
        #ordering by author, author with pk=1 will show first
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

#@login_required
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
    def form_valid(self, form): 
        form.instance.author = self.request.user
        return super().form_valid(form)
        
# class SortStoryView(generic.DetailView):
#     model = NewsStory
#     template_name = 'news/sort.html'
#     context_object_name = 'sort'

she_codes_news/user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm

from django.contrib.auth.decorators import login_required

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'user/createAccount.html'

@login_required
#This is a decorator that add functionality to our def, therefore the user needs to be logged in to access this view
def profile(request):

    if request.method == 'POST':
        u_form = CustomUserChangeForm(request.POST, request.FILES,  instance=request.user) #passing the instance so the details of the user are prepopulated

        if u_form.is_valid():
            u_form.save()
            #messages.sucess(request, f'Your account has been updated!')
            #return redirect('profile')

    else:
        u_form = CustomUserChangeForm(instance=request.user) #passing the instance so the details of the user are prepopulated
   
    context = {
        'u_form': u_form
    }
    return render(request, 'user/profile.html', context)
    
# class UserDetailView(generic.DetailView):
#     model = CustomUser
#     template_name = 'user/sort.html'
#     context_object_name = 'sort'


# Create your views here.

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %} 

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% block stylesheets %}{% endblock %}

{% block content %} 
 
<form id="form" action="" method="post"> 

    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" value="submit" style="color:  #191970;"> 
</form> 
    
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}    

{% block content %}    

    <p>During this hard times, the world needs more happy news</p>
    <p>Browse below for puppies and cute animals in general</p>
    <p>The endgame is to put a smile on your face. Happy browsing &#128515</p>
    
    <h2>Latest News</h2>
    

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
        
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>



    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %} 
{% load static %} 
 
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% endblock %}
 
{% block content %} 


<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src= {{ story.image_url }}> 
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %} 

she_codes_news/news/templates/news/storyCard.html
{% load static %} 

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% endblock %}

<div class="story-card" id="story-card-{{ position }}">
    <a href="{%url 'news:story' story.id %}">
        <img src= {{ story.image_url}}>
        <!-- {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src= {{ story.image_url}}>
        {% endif %} -->
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date|date }}</h4>

        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Happy News</title>
        <meta name="description" content="">
        <meta name="author" content="Albany A.">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>Happy News</h1>

            </div>
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}

        
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'user:profile' %}">{{ request.user.username }}</a>
        <a href="{% url 'news:newStory' %}">Write a new happy post</a> 
        <a href="{% url 'logout' %}">Logout</a>
    
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'user:createAccount' %}">Create Account</a>
        {# createAccount is the name given to the view in user urls #}
       
    {% endif %}

</nav>

she_codes_news/user/templates/user/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post" enctype="multipart/form-data"> {# the enctype is needed so we can save images#}
    {% csrf_token %}
    {{ form.as_p }} 
    <button type="submit">Create Account</button>
</form>

<!-- Added this here to provide the option to sign in if the user already has an account -->
<!-- <p>Already have an account?</p>
<a href="#"> Sign In </a>  -->
<!-- Need to add proper link on href, for the time being it is a placeholder -->

{% endblock %}

she_codes_news/user/templates/user/profile.html
{% extends 'base.html' %}



{% block content %}

    <div class="content-section">
        <div>
            <img class="account-img" src="{{ user.image.url }}">
            <div>
                <h2 class="account-heading">{{ user.username }}</h2>
                <p>Email: {{ user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
        
        <h4 style = "font-family: 'Permanent Marker', cursive;"> <br> <br> Update your deets below: </h4>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ u_form.as_p }} 
            <button type="submit">Update</button>
        </form>
    </div>
{% endblock %}